-- =========================================================
-- DAPOERSARI PROJECT 2 — DATABASE SETUP
-- Menggunakan database Supabase yang SAMA dengan Project 1.
-- Tidak membuat tabel transaksi baru.
-- =========================================================

-- 1) Pastikan role owner tersedia pada profiles.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.profiles'::regclass
      AND conname = 'profiles_role_check'
  ) THEN
    ALTER TABLE public.profiles DROP CONSTRAINT profiles_role_check;
  END IF;
EXCEPTION WHEN undefined_table THEN
  NULL;
END $$;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('customer', 'cashier', 'owner'));

-- 2) Pengeluaran usaha.
CREATE TABLE IF NOT EXISTS public.expenses (
  id bigint generated by default as identity primary key,
  expense_date date NOT NULL DEFAULT CURRENT_DATE,
  category text NOT NULL,
  description text NOT NULL,
  amount numeric(14,2) NOT NULL CHECK (amount >= 0),
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_expenses_date
  ON public.expenses (expense_date DESC);

CREATE INDEX IF NOT EXISTS idx_expenses_category
  ON public.expenses (category);

-- 3) Pengaturan owner.
CREATE TABLE IF NOT EXISTS public.financial_settings (
  id bigint generated by default as identity primary key,
  business_name text NOT NULL DEFAULT 'Dapoersari',
  shopeefood_platform_rate numeric(5,2) NOT NULL DEFAULT 25
    CHECK (shopeefood_platform_rate >= 0 AND shopeefood_platform_rate <= 100),
  target_daily_sales numeric(14,2) NOT NULL DEFAULT 0 CHECK (target_daily_sales >= 0),
  target_monthly_sales numeric(14,2) NOT NULL DEFAULT 0 CHECK (target_monthly_sales >= 0),
  updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.financial_settings (id, business_name, shopeefood_platform_rate)
VALUES (1, 'Dapoersari', 25)
ON CONFLICT (id) DO NOTHING;

-- 4) RLS. Project 2 backend memakai SERVICE ROLE di server setelah
--    autentikasi token + pengecekan role owner.
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owner can manage expenses" ON public.expenses;
CREATE POLICY "Owner can manage expenses"
ON public.expenses
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role = 'owner'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role = 'owner'
  )
);

DROP POLICY IF EXISTS "Owner can manage financial settings" ON public.financial_settings;
CREATE POLICY "Owner can manage financial settings"
ON public.financial_settings
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role = 'owner'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role = 'owner'
  )
);

-- 5) Jadikan akun tertentu sebagai owner.
--    Ganti EMAIL_OWNER sesuai akun kamu.
-- UPDATE public.profiles
-- SET role = 'owner'
-- WHERE id = (SELECT id FROM auth.users WHERE email = 'EMAIL_OWNER');

-- 6) Validasi sumber transaksi Project 1.
SELECT sales_channel, COUNT(*) AS jumlah_transaksi, COALESCE(SUM(total),0) AS omzet
FROM public.orders
GROUP BY sales_channel
ORDER BY sales_channel;
